<a href="https://colab.research.google.com/github/DhiaDerbeli/Machine_Learning/blob/main/Perceptron_Probabiliste.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [64]:
import numpy as np
import random
from math import exp

In [65]:
def predict(a) :
  phi = random.uniform(0,1)
  proba = 1/(1 + exp(-a))
  if phi < proba :
    return 1
  return 0



In [66]:
for i in range(len(predicted)):
  for j in range(len(predicted[0])):
    predicted[i][j] = predict(predicted[i][j])

In [74]:
x = np.array([[1,0,1],[1,1,0],[0,0,1],[0,1,1]])
t = np.array([[0,0,1],[1,1,1],[0,1,0]])
v = np.array([[0.9,0.78,0.64],[-0.54,0.52,-0.11],[0.21,-0.09,0.23],[-0.03,0.96,0.58]])
predicted = np.matmul(np.transpose(v),x)
learning_rate = 0.75
iteration = 0
for i in range(len(predicted)):
  for j in range(len(predicted[0])):
    predicted[i][j] = predict(predicted[i][j])
while(np.array_equal(predicted,t) == False):
  iteration = iteration + 1
  v = v + learning_rate*np.matmul(x, np.transpose(t-predicted))
  predicted = np.matmul(np.transpose(v),x)
  for i in range(len(predicted)):
    for j in range(len(predicted[0])):
      predicted[i][j] = predict(predicted[i][j])

In [75]:
print("learning rate : ", learning_rate)
print("number of iterations : ", iteration)
print("matrix v : ")
print(v)
print()
print("predictions : ")
print(predicted)

learning rate :  0.75
number of iterations :  7
matrix v : 
[[ 0.9   3.03 -1.61]
 [-3.54  1.27  1.39]
 [ 1.71  1.41 -1.27]
 [-0.03  2.46  1.33]]

predictions : 
[[0. 0. 1.]
 [1. 1. 1.]
 [0. 1. 0.]]


In [70]:
#learning rate = 0.3 , matrix formula
x = np.array([[1,0,1],[1,1,0],[0,0,1],[0,1,1]])
t = np.array([[0,0,1],[1,1,1],[0,1,0]])
v = np.array([[0.9,0.78,0.64],[-0.54,0.52,-0.11],[0.21,-0.09,0.23],[-0.03,0.96,0.58]])
iteration = 0
v = np.array([[0.9,0.78,0.64],[-0.54,0.52,-0.11],[0.21,-0.09,0.23],[-0.03,0.96,0.58]])
predicted = np.matmul(np.transpose(v),x)
learning_rate = 0.3
for i in range(len(predicted)):
  for j in range(len(predicted[0])):
    predicted[i][j] = predict(predicted[i][j])
while(np.array_equal(predicted,t) == False):
  iteration = iteration + 1
  v = v + learning_rate*np.matmul(x, np.transpose(t-predicted))
  predicted = np.matmul(np.transpose(v),x)
  for i in range(len(predicted)):
    for j in range(len(predicted[0])):
      predicted[i][j] = predict(predicted[i][j])

In [71]:
print("learning rate : ", learning_rate)
print("number of iterations : ", iteration)
print("matrix v : ")
print(v)
print()
print("predictions : ")
print(predicted)

learning rate :  0.3
number of iterations :  10
matrix v : 
[[ 0.6   1.68 -1.46]
 [-2.64  0.82  0.19]
 [ 1.11  0.51 -0.97]
 [-0.03  1.56  0.58]]

predictions : 
[[0. 0. 1.]
 [1. 1. 1.]
 [0. 1. 0.]]
