In [12]:
import numpy as np

In [13]:
x = np.array([[1,0,1],[1,1,0],[0,0,1],[0,1,1,]])
t = np.array([[0,0,1],[1,1,1],[0,1,0]])
v = np.array([[0.9,0.78,0.64],[-0.54,0.52,-0.11],[0.21,-0.09,0.23],[-0.03,0.96,0.58]])
iteration = 0
learning_rate = 0.75
predicted = np.matmul(np.transpose(v),x)
for i in range(len(predicted)):
  for j in range(len(predicted[0])):
    if predicted[i][j] < 0 :
      predicted[i][j] = 0
    else : 
      predicted[i][j] = 1
while(np.array_equal(predicted,t) == False):
  iteration = iteration + 1
  v = v + learning_rate*np.matmul(x, np.transpose(t-predicted))
  predicted = np.matmul(np.transpose(v),x)
  for i in range(len(predicted)):
    for j in range(len(predicted[0])):
      if predicted[i][j] < 0 :
        predicted[i][j] = 0
      else : 
        predicted[i][j] = 1

In [14]:
print("learning rate : ", learning_rate)
print("number of iterations : ", iteration)
print("matrix v : ")
print(v)
print()
print("predictions : ")
print(predicted)

learning rate :  0.75
number of iterations :  2
matrix v : 
[[ 0.15  0.78 -0.86]
 [-1.29  0.52 -0.11]
 [ 0.21 -0.09 -0.52]
 [-0.03  0.96  0.58]]

predictions : 
[[0. 0. 1.]
 [1. 1. 1.]
 [0. 1. 0.]]


In [15]:
x = np.array([[1,0,1],[1,1,0],[0,0,1],[0,1,1,]])
t = np.array([[0,0,1],[1,1,1],[0,1,0]])
v = np.array([[0.9,0.78,0.64],[-0.54,0.52,-0.11],[0.21,-0.09,0.23],[-0.03,0.96,0.58]])
iteration = 0
learning_rate = 0.3
predicted = np.matmul(np.transpose(v),x)
for i in range(len(predicted)):
  for j in range(len(predicted[0])):
    if predicted[i][j] < 0 :
      predicted[i][j] = 0
    else : 
      predicted[i][j] = 1
while(np.array_equal(predicted,t) == False):
  iteration = iteration + 1
  v = v + learning_rate*np.matmul(x, np.transpose(t-predicted))
  predicted = np.matmul(np.transpose(v),x)
  for i in range(len(predicted)):
    for j in range(len(predicted[0])):
      if predicted[i][j] < 0 :
        predicted[i][j] = 0
      else : 
        predicted[i][j] = 1

In [16]:
print("learning rate : ", learning_rate)
print("number of iterations : ", iteration)
print("matrix v : ")
print(v)
print()
print("predictions : ")
print(predicted)

learning rate :  0.3
number of iterations :  2
matrix v : 
[[ 0.6   0.78 -0.26]
 [-0.84  0.52 -0.11]
 [ 0.21 -0.09 -0.37]
 [-0.03  0.96  0.28]]

predictions : 
[[0. 0. 1.]
 [1. 1. 1.]
 [0. 1. 0.]]
