<a href="https://colab.research.google.com/github/DhiaDerbeli/Machine_Learning/blob/main/Retropropagation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [73]:
import numpy as np
import random
from math import exp

In [86]:
min_error = 0.001
learning_rate = 0.3
def f(a) :
  phi = random.uniform(0,1)
  proba = 1/(1 + exp(-a))
  return proba

def matrix_update(matrix, delta, x) :
  rslt = matrix + learning_rate*np.matmul(delta , np.transpose(x))
  return rslt

def compute_delta(h, error):
  return np.multiply(np.multiply(h,(1-h)), error)

def still_learning(t, o):
  diff = np.abs(t - o)
  verif = diff < min_error
  if(verif.all()) :
    return False

  return True

In [89]:
x = np.array([[1], [2], [3]])
t = np.array([[0.1] ,[0.3], [0.7]])
w = np.array([[0.5, 0.3, 0.1], [0.3, 0.2, 0.1]])
z = np.array([[0.1, 0.2], [0.3, 0.4], [0.5, 0.6]])


b = np.matmul(w,x)
h = np.vectorize(f)(b)
a = np.matmul(z,h)
o = np.vectorize(f)(a)

In [90]:
learning_rate = 0.3
iteration = 0
while(still_learning(o,t)) :
  iteration = iteration + 1
  delta_out = compute_delta(o,t-o)
  delta_hidden = compute_delta(h, np.matmul(np.transpose(z),delta_out))
  z = matrix_update(z, delta_out, h)
  w = matrix_update(w, delta_hidden, x)
  b = np.matmul(w,x)
  h = np.vectorize(f)(b)
  a = np.matmul(z,h)
  o = np.vectorize(f)(a)

In [91]:
print("learning rate : ", learning_rate)
print("number of iterations : ", iteration)
print("matrix w : ")
print(w)
print()
print("matrix z : ")
print(z)
print()
print("predictions : ")
print(o)

learning rate :  0.3
number of iterations :  862
matrix w : 
[[0.59788588 0.49577175 0.39365763]
 [0.37758088 0.35516177 0.33274265]]

matrix z : 
[[-1.3308668  -1.04970468]
 [-0.57092903 -0.34865358]
 [ 0.41054717  0.51834666]]

predictions : 
[[0.10099824]
 [0.29997438]
 [0.70003023]]


In [92]:
x = np.array([[1], [2], [3]])
t = np.array([[0.1] ,[0.3], [0.7]])
w = np.array([[0.5, 0.3, 0.1], [0.3, 0.2, 0.1]])
z = np.array([[0.1, 0.2], [0.3, 0.4], [0.5, 0.6]])

b = np.matmul(w,x)
h = np.vectorize(f)(b)
a = np.matmul(z,h)
o = np.vectorize(f)(a)

In [93]:
learning_rate = 0.75
iteration = 0
while(still_learning(o,t)) :
  iteration = iteration + 1
  delta_out = compute_delta(o,t-o)
  delta_hidden = compute_delta(h, np.matmul(np.transpose(z),delta_out))
  z = matrix_update(z, delta_out, h)
  w = matrix_update(w, delta_hidden, x)
  b = np.matmul(w,x)
  h = np.vectorize(f)(b)
  a = np.matmul(z,h)
  o = np.vectorize(f)(a)

In [94]:
print("learning rate : ", learning_rate)
print("number of iterations : ", iteration)
print("matrix w : ")
print(w)
print()
print("matrix z : ")
print(z)
print()
print("predictions : ")
print(o)

learning rate :  0.75
number of iterations :  343
matrix w : 
[[0.59737509 0.49475018 0.39212527]
 [0.37627586 0.35255173 0.32882759]]

matrix z : 
[[-1.33408001 -1.04906301]
 [-0.57260179 -0.34785009]
 [ 0.41113557  0.51896697]]

predictions : 
[[0.10099592]
 [0.29997381]
 [0.700031  ]]
