<a href="https://colab.research.google.com/github/DhiaDerbeli/Machine_Learning/blob/main/TP_machine_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [81]:
import numpy as np

In [82]:
x = np.array([[1,0,1],[1,1,0],[0,0,1],[0,1,1,]])

In [83]:
t = np.array([[0,0,1],[1,1,1],[0,1,0]])

In [84]:
v = np.array([[0.9,0.78,0.64],[-0.54,0.52,-0.11],[0.21,-0.09,0.23],[-0.03,0.96,0.58]])

In [85]:
predicted = np.matmul(np.transpose(v),x)

In [86]:
learning_rate = 0.75


In [87]:
for i in range(len(predicted)):
  for j in range(len(predicted[0])):
    if predicted[i][j] < 0 :
      predicted[i][j] = 0
    else : 
      predicted[i][j] = 1

In [88]:
while(np.array_equal(predicted,t) == False):
  v = v + learning_rate*np.matmul(x, np.transpose(t-predicted))
  predicted = np.matmul(np.transpose(v),x)
  for i in range(len(predicted)):
    for j in range(len(predicted[0])):
      if predicted[i][j] < 0 :
        predicted[i][j] = 0
      else : 
        predicted[i][j] = 1

In [91]:
# learning rate = 0.75 , matrix formula :
print(v)

[[ 0.15  0.78 -0.86]
 [-1.29  0.52 -0.11]
 [ 0.21 -0.09 -0.52]
 [-0.03  0.96  0.58]]


In [93]:
#learning rate = 0.3 , matrix formula
v = np.array([[0.9,0.78,0.64],[-0.54,0.52,-0.11],[0.21,-0.09,0.23],[-0.03,0.96,0.58]])
predicted = np.matmul(np.transpose(v),x)
learning_rate = 0.3
for i in range(len(predicted)):
  for j in range(len(predicted[0])):
    if predicted[i][j] < 0 :
      predicted[i][j] = 0
    else : 
      predicted[i][j] = 1
while(np.array_equal(predicted,t) == False):
  v = v + learning_rate*np.matmul(x, np.transpose(t-predicted))
  predicted = np.matmul(np.transpose(v),x)
  for i in range(len(predicted)):
    for j in range(len(predicted[0])):
      if predicted[i][j] < 0 :
        predicted[i][j] = 0
      else : 
        predicted[i][j] = 1
print(v)

[[ 0.6   0.78 -0.26]
 [-0.84  0.52 -0.11]
 [ 0.21 -0.09 -0.37]
 [-0.03  0.96  0.28]]
